os: linux
sudo: required
language:
  - minimal
services:
  - docker
  
compiler:
  -gcc

before_install:
  - pip install --user cpp-coveralls

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-8" CC="gcc-8"; fi
  - mkdir build
  - cd build
  - cmake ..
  - make

node_js:
  - 8

notifications:
  email: false

jobs:
  include:
    - name: "checks"
      script:
        - chmod 755 scripts/*.sh
        - docker run -v `pwd`:`pwd` -w `pwd` -t rusdevops/bootstrap-cpp scripts/checks.sh   
    - name: "tests"
      script:
        - ./tests
